#!/bin/bash
# DO NOT EDIT THIS FILE

TARGETS="command.cmo state.cmo main.cmo test.cmo"

ocamlbuild -use-ocamlfind $TARGETS
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING

Your code currently does not compile.  You will receive
little to no credit for submitting this code. Check the
error messages above carefully to determine what is wrong.
See a consultant for help if you cannot determine what is
wrong.
===========================================================
EOF
  exit 1
fi

